name: Lint C# Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dotnet-lint
        run: dotnet tool install --global dotnet-lint
      - name: Run dotnet-lint
        run: dotnet-lint --path .
